# Generated by Django 5.2.9 on 2026-01-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_subscription_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="clouds",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="description",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="feels_like",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="humidity",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="pressure",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="visibility",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="wind_deg",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="wind_speed",
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="data",
            field=models.JSONField(
                default=list, help_text="Weather data as JSON array"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="forecast_period",
            field=models.CharField(
                choices=[
                    ("current", "Current"),
                    ("hourly", "Hourly"),
                    ("today", "Today"),
                    ("tomorrow", "Tomorrow"),
                    ("3days", "3 Days"),
                    ("week", "Week"),
                    ("8days", "8 Days"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="forecast_period",
            field=models.CharField(
                choices=[
                    ("current", "Current"),
                    ("hourly", "Hourly"),
                    ("today", "Today"),
                    ("tomorrow", "Tomorrow"),
                    ("3days", "3 Days"),
                    ("week", "Week"),
                    ("8days", "8 Days"),
                ],
                max_length=20,
            ),
        ),
    ]
