# Generated by Django 5.2.9 on 2026-01-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_weatherdata_clouds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="forecast_period",
            field=models.CharField(
                choices=[
                    ("current", "Current"),
                    ("hourly", "Hourly"),
                    ("today", "Today"),
                    ("tomorrow", "Tomorrow"),
                    ("3days", "3 Days"),
                    ("week", "Week"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="forecast_period",
            field=models.CharField(
                choices=[
                    ("current", "Current"),
                    ("hourly", "Hourly"),
                    ("today", "Today"),
                    ("tomorrow", "Tomorrow"),
                    ("3days", "3 Days"),
                    ("week", "Week"),
                ],
                max_length=20,
            ),
        ),
    ]
